---
title: "Analiza datasetu - cechy"
author: "Joanna Gajewska & Olaf Werner & Bogdan Jastrzębski"
date: "April 14, 2019"
output: html_document
---

# 1. Wstępna analiza zbioru danych

---

W tej części znajduje się przeprowadzona przez nas analiza dostępnego 
zbioru danych. Zinterpretowaliśmy cechy rekordów, ich znaczenie, a także
rozmaite flagi wykorzystane przez autorów, do oznaczania braków, nieścisłości etc. 

***

## 1.1 Flagi

---

W danych pojawiają się następujące flagi:

* -9 - brak zapisu biurowego lub brak prześledzenia

* -8 - brak użytecznych/ważnych kredytów lub recenzji kredytu

* -7 - warunek niespełniony

`-9` oznacza zwykły brak danych, brak zapisu o czymś. 
Zwykle kiedy w rekordzie pojawiała się flaga `-9`, pojawiała
się we wszystkich kolumnach rekordu. Takich rekordów było 558 na 10 459 wszystkich rekordów datasetu. Te rekordy _usunęliśmy_.

`-8` oznacza brak danych użytecznych. W odróżnieniu od `-9` ta flaga nie
pojawiała się w całym rekordzie. Ponieważ liczba rekordów zawierających 
tę flagę była bardzo duża, braki te imputowaliśmy (patrz roz. N).

Flaga `-7` pojawiała się wtedy, gdy dla danego kredytobiorcy danych 
nie da się logicznie uzupełnić, np. jeżeli dana kolumna podaje czas od 
ostatniego spóźnienia w spłacaniu kredytu, podczas gdy kredytobiorca nie 
spóźnił się ani razu. Z oczywistych względów mierzenie czasu, który
upłynął od zdarzenia, które nie zaszło, jest nielogiczne.

***

## 1.2 Flagi - krótkie zestawienie

Oto jak przedstawia się udział poszczególnych flag w różnych kolumnach:

| Nazwa kolumny | *-9* | *-8* | *-7* |
|---|---|---|---|
| ExternalRiskEstimate               | 10 | 0  | 0  |
| MSinceOldestTradeOpen              | 0  | 239| 0  |
| MSinceMostRecentDelq               | 0  | 176|4664|
| MSinceMostRecentInqexcl7days       | 0  | 476|1855|
| NetFractionRevolvingBurden         | 0  | 186| 0  |
| NetFractionInstallBurden           | 0  |3419| 0  |
| NumRevolvingTradesWBalance         | 0  | 156| 0  |
| NumInstallTradesWBalance           | 0  | 861| 0  |
| NumBank2NatlTradesWHighUtilization | 0  | 583| 0  |
| PercentTradesWBalance              | 0  | 18 | 0  |

Jak widać przeciętnie dane występują w małej liczności w stosunku do 
wielkości zbioru danych (10 459), jednak kilka kolumn zawiera flag bardzo dużo. W sumie wierszy bez flag `-9`, `-8` i `-7` jest 2502, czyli zaledwie $\frac{1}{4}$ zbioru.

## 1.3 Interpretacja i analiza cech

### Risk Performance

Zbiór wartości: {Good, Bad}

* -9 : 0

* -8 : 0

* -7 : 0

Czy zapłacono w terminie umowy? (12-36 miesięcy) 

Watrość przez nas przewidywana. Odpowiada na pytanie, czy klient spłacił 
kredyt w wyznaczonym terminie.

### External Risk Estimate

Zbiór wartości: 0-100%

* -9 : 0

* -8 : 239

* -7 : 0

Zewnętrzna ocena kredytobiorcy. Złożenie wielu nieznananych znaczników,
działających na korzyść bądź niekorzyść kredytobiorcy. 

### Months Since Oldest Trade Open

Zbiór wartości: 0-100%

* -9 : 0

* -8 : 239

* -7 : 0

Liczba miesięcy od otwarcia najstarszego kredytu.

### Months Since Most Recent Trade Open 

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0  

* -8 : 239  

* -7 : 0

Liczba miesięcy od otwarcia ostatniego kredytu.

### Average Months in File

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 0

* -7 : 0

Średni czas zadłużenia.


### Number Satisfactory Trades

Zbiór wartości: $\mathcal{R}_+$

* -9 : 0

* -8 : 0

* -7 : 0

Liczba spłaconych kredytów.

### Number Trades 60+ Ever

Zbiór wartości: $\mathcal{R}_+$

* -9 : 0

* -8 : 0

* -7 : 0

Liczba kredytów ponad 60 tys.

### Number Trades 90+ Ever

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 0

* -7 : 0

Liczba kredytów ponad 90 tys.

### Percent Trades Never Delinquent  

Zbiór wartości: 0-100%

* -9 : 0

* -8 : 0

* -7 : 0

Procent kredytów nigdy niezaległych.

### Months Since Most Recent Delinquency               

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 176

* -7 : 4664

Liczba miesięcy od ostatniego opóźnienia.

###

###


### Number Total Trades                    

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 0

* -7 : 0

Całkowita liczba kredytów lub inaczej liczba kont kredytowych.

### Number Trades Open in Last 12 Months          

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 0

* -7 : 0

Liczba kredytów zaciągniętych podczas ostatnich dwunastu miesięcy.

### Percent Installment Trades              

Zbiór wartości: 0-100%

* -9 : 0

* -8 : 0

* -7 : 0

Odsetek kredytów, które były ratalne tj. spłacane w ratach. 

### Months Since Most Recent Inq. Excl. 7 days      

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 476

* -7 : 1855

Liczba miesięcy od ostatniego sprawdzenia kredytu (przekraczające 7 dni).

### Number Inq. Last 6 Months                      

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 0

* -7 : 0

Liczba sprawdzeń kredytu podczas ostatnich 6 miesięcy.

### Number Inq. Last 6 Months excl. 7 days             

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 0

* -7 : 0

Liczba sprawdzeń kredtu przekaraczających 7 dni. 

### Net Fraction Revolving Burden

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 186

* -7 : 0

Udział kredytów rolowanych w obciążeniu kredytowym. 

### Net Fraction Installment Burden

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 3419

* -7 : 0

Udział kredytów ratalnych w obciążeniu kredytowym.

### Number of Revolving Trades With Balance

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 156

* -7 : 0

Liczba kredytów rolowanych z "balonem", czyli ostateczną dużą spłatą. 
Oczywiście kredytów rolowanych się często wcale nie spłaca,
ewentualnie np. kiedy bank uzna, że ryzyko jest zbyt duże, by przedłużać 
kredyt dalej.

### Number of Installment Trades With Balance

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 861

* -7 : 0

Liczba kredytów ratalnych ze zbalansowaniem pod koniec, jak wyżej.

### NumBank2NatlTradesWHighUtilization

Zbiór wartości: 0, 1, 2, 3…

* -9 : 0

* -8 : 583

* -7 : 0

Liczba kredytów o dużym zysku.

###  Percent of Trades With Balance


Zbiór wartości: 0-100%

* -9 : 0

* -8 : 18

* -7 : 0

Procent kredytów zbalansowanych, z "balonem".







